name: Build

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' 
          java-version: '17'
      - name: Set up Node JS
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Test consumer siren project (js)
        run: |
          npm install
          npm test
      - name: Test consumer siren project (java)
        run: |
          mvn test
      - name: Test provider siren project (java)
        run: |
          ./gradlew pactverify
